config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :bookmarks do
    get :search, on: :collection
  end

  resources :tags, only: [] do
    get :search, on: :collection
  end

  resources :unfurls, only: [:index]

  root to: "bookmarks#index"

  get "/health", to: proc { [200, {}, ["OK"]] }
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
# frozen_string_literal: true

class Bookmark < ApplicationRecord
  include Taggable

  belongs_to :user

  validates :url, presence: true
end

app/models/concerns/taggable.rb
# frozen_string_literal: true

require "active_support/concern"

module Taggable
  extend ActiveSupport::Concern

  included do
    has_many :taggings, -> { includes(:tag).order(:created_at) },
             as: :taggable,
             dependent: :destroy,
             inverse_of: :taggable

    has_many :tags, through: :taggings

    after_save :save_tags

    attr_writer :tag_list

    def tag_list
      @tag_list = tags.map(&:name).join(", ")
    end

    def save_tags
      self.tags = @tag_list.to_s.split(",").map do |tag_name|
        Tag.find_or_create_by!(name: tag_name.strip)
      end
    end
  end

  class_methods do
    def tagged_with(values)
      where("id IN (#{taggable_ids_query(values).to_sql})")
    end

    private

    def taggable_ids_query(values)
      Tagging.joins(:tag).select(:taggable_id)
             .where(taggable_type: name)
             .where(tags: { name: values })
             .having("COUNT(*) = #{values.length}")
             .group(:taggable_id)
    end
  end
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
end

app/models/tagging.rb
# frozen_string_literal: true

class Tagging < ApplicationRecord
  belongs_to :tag, counter_cache: true
  belongs_to :taggable, polymorphic: true

  after_destroy :remove_unused_tags

  private

  def remove_unused_tags
    tag.destroy if tag.reload.taggings_count.zero?
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :omniauthable, :timeoutable
  devise :confirmable, :database_authenticatable, :lockable, :recoverable,
         :registerable, :rememberable, :trackable, :validatable

  has_person_name

  has_many :bookmarks, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    extra_keys = %i(
      first_name last_name
    )
    signup_keys = extra_keys
    devise_parameter_sanitizer.permit(:sign_up, keys: signup_keys)
    devise_parameter_sanitizer.permit(:account_update, keys: extra_keys)
  end
end

app/controllers/bookmarks_controller.rb
# frozen_string_literal: true

class BookmarksController < ApplicationController
  include Pagy::Backend

  before_action :authenticate_user!
  before_action :set_bookmark, only: %i(show edit update destroy)

  def index
    @pagy, @bookmarks = pagy(
      current_user.bookmarks.includes(:tags).order(created_at: :desc).all, items: 25,
    )
  end

  def show; end

  def new
    @bookmark = current_user.bookmarks.new
  end

  def edit; end

  def create
    @bookmark = current_user.bookmarks.new(bookmark_params)

    if @bookmark.save
      redirect_to @bookmark, notice: t(".success")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @bookmark.update(bookmark_params)
      redirect_to @bookmark, notice: t(".success")
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to bookmarks_path, notice: t(".success"), status: :see_other
  end

  def search
    @pagy, @bookmarks = pagy(
      current_user.bookmarks.includes(:tags, :taggings)
              .tagged_with(tags_from_params)
              .order(created_at: :desc),
      items: 10,
    )

    render "index"
  end

  private

  def set_bookmark
    @bookmark = current_user.bookmarks.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:notes, :tag_list, :title, :url)
  end

  def tags_from_params
    params[:q].split(",").map(&:strip)
  end
end

app/controllers/tags_controller.rb
# frozen_string_literal: true

class TagsController < ApplicationController
  include Pagy::Backend

  before_action :authenticate_user!

  def search
    @pagy, @tags = pagy(
      Tag.where("name ILIKE ?", "#{params[:q]}%")
         .order(name: :asc).all,
    )

    render json: @tags.to_json
  end
end

app/controllers/unfurls_controller.rb
# frozen_string_literal: true

class UnfurlsController < ApplicationController
  before_action :authenticate_user!

  def index
    page = MetaInspector.new(
      url_from_params,
    )

    render json: page.to_json
  end

  private

  def url_from_params
    CGI.unescape(params[:url])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

require "rouge/plugins/redcarpet"

class HTML < Redcarpet::Render::HTML
  include Rouge::Plugins::Redcarpet
end

module ApplicationHelper
  include Pagy::Frontend

  def feather_icon(name, options = {})
    content_tag(
      :i,
      nil,
      options.deep_merge(
        data: {
          feather: name,
          controller: "feather",
        },
      ),
    )
  end

  def markdown(text)
    renderer = HTML.new(markdown_options)
    markdown = Redcarpet::Markdown.new(renderer, markdown_extensions)
    markdown.render(text)
  end

  private

  def markdown_extensions
    {
      autolink: true,
      superscript: true,
      fenced_code_blocks: true,
    }
  end

  def markdown_options
    {
      filter_html: true,
      hard_wrap: true,
      link_attributes: { rel: "nofollow", target: "_blank" },
      space_after_headers: true,
    }
  end
end

app/helpers/bookmarks_helper.rb
# frozen_string_literal: true

module BookmarksHelper
  def options_for_tags
    Tag.order(name: :asc).all.map do |tag|
      { id: tag.id, name: tag.name }
    end
  end
end

app/helpers/flash_helper.rb
# frozen_string_literal: true

module FlashHelper
  def classes_for_flash(flash_type)
    case flash_type.to_sym
    when :error, :alert
      "bg-red-100 text-red-700"
    else
      "bg-blue-100 text-blue-700"
    end
  end
end

app/views/bookmarks/_bookmark.html.erb
<div class="w-full relative rounded-2xl shadow-lg bg-white border border-gray-100 flex flex-col justify-between">
  <div class="flex flex-col gap-4 px-5 py-4">
    <div>
      <h2 class="text-xl font-medium">
        <%= link_to bookmark.title, bookmark %>
      </h2>
      <div class="text-sm truncate text-gray-600">
        <%= link_to bookmark.url, bookmark.url, target: "_blank" %>
      </div>
    </div>
    <% if bookmark.tags.any? %>
      <div>
        <% bookmark.tags.each do |tag| %>
          <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800">
            <%= tag.name %>
          </span>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="flex flex-row justify-end gap-2 border-t border-gray-300 px-6 py-4">
    <%= button_to bookmark, data: { turbo_confirm: 'Are you sure?' }, method: :delete, class: 'inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50' do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
        <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
      </svg>
    <% end %>
    <%= link_to 'Edit', edit_bookmark_path(bookmark), class: 'inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50' %>
    <%= link_to 'Show', bookmark, class: 'inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50' %>
  </div>
</div>

app/views/bookmarks/_form.html.erb
<%= turbo_frame_tag @bookmark do %>
  <%= form_for @bookmark, data: { controller: 'markdown unfurl bookmark-form', action: 'unfurl:update.title->bookmark-form#updateTitle unfurl:update.notes->markdown#updateContent' } do |f| %>
    <div class="space-y-12">
      <% if @bookmark.errors.any? %>
        <div class="rounded-md bg-red-50 p-4">
          <div class="flex">
            <div class="flex-shrink-0">
              <svg class="h-5 w-5 text-red-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.28 7.22a.75.75 0 00-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 101.06 1.06L10 11.06l1.72 1.72a.75.75 0 101.06-1.06L11.06 10l1.72-1.72a.75.75 0 00-1.06-1.06L10 8.94 8.28 7.22z" clip-rule="evenodd" />
              </svg>
            </div>
            <div class="ml-3">
              <h3 class="text-sm font-medium text-red-800"> <%= pluralize(@bookmark.errors.count, "error") %> prohibited this bookmark from being saved</h3>
              <div class="mt-2 text-sm text-red-700">
                <ul role="list" class="list-disc space-y-1 pl-5">
                  <% @bookmark.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <div>
        <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
          <div class="sm:col-span-6">
            <%= f.label :title, class: 'block text-sm font-medium leading-6 text-gray-900' %>
            <div class="mt-2">
              <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600">
                <%= f.text_field :title, class: 'block flex-1 border-0 bg-transparent text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6', data: { unfurl_target: 'title', bookmark_form_target: 'title' } %>
              </div>
            </div>
          </div>
          <div class="sm:col-span-6">
            <%= f.label :url, class: 'block text-sm font-medium leading-6 text-gray-900' %>
            <div class="mt-2">
              <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600">
                <%= f.text_area :url, class: 'block flex-1 border-0 bg-transparent text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6', data: { unfurl_target: 'url' } %>
              </div>
              <button type="button" data-action="unfurl#fetch" class="mt-3 text-sm leading-6 text-gray-600">Unfurl?</button>
            </div>
          </div>
          <div class="sm:col-span-6">
            <%= f.label :tag_list, class: 'block text-sm font-medium leading-6 text-gray-900' %>
            <div class="mt-2">
              <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600">
                <%= f.text_field :tag_list, class: 'block flex-1 border-0 p-1 bg-transparent text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6', value: @bookmark.tags.map(&:name).join(','), data: { controller: 'tags-list', tags_list_autocomplete_url_value: search_tags_path, unfurl_target: 'tagsList' } %>
              </div>
            </div>
          </div>
          <div class="col-span-full prose z-20">
            <%= f.label :notes, class: "block text-sm font-medium leading-6 text-gray-900" %>
            <div class="mt-2">
              <%= f.text_area :notes, class: 'block w-full rounded-md border-0 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6', data: { markdown_target: 'textarea', unfurl_target: 'notes' }, rows: 6 %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="mt-6 flex items-center gap-2">
      <%= link_to 'Back', bookmarks_path, class: 'inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50' %>
      <%= f.submit class: "cursor-pointer inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-gray-700 hover:bg-gray-800" %>
    </div>
  <% end %>
<% end %>

app/views/bookmarks/edit.html.erb
<div class="mx-auto max-w-2xl py-14">
  <div>
    <h1 class="text-3xl font-semibold text-gray-900 mb-2">Edit Bookmark</h1>
  </div>
  <%= render 'form' %>
</div>

app/views/bookmarks/index.html.erb
<% if @bookmarks.any? %>
  <div class="flex flex-col gap-12 mb-12">
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
      <%= render @bookmarks %>
    </div>
    <div>
      <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
    </div>
  </div>
<% else %>
  <div class="text-center h-full flex items-center flex-col justify-center">
    <svg class="mx-auto h-12 w-12 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
      <path vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 13h6m-3-3v6m-9 1V7a2 2 0 012-2h6l2 2h6a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2z" />
    </svg>
    <h3 class="mt-2 text-base font-semibold text-gray-900">No bookmarks found</h3>
    <p class="mt-1 text-sm text-gray-500">Get started by creating a new bookmark.</p>
    <div class="mt-6">
      <%= link_to new_bookmark_path, class: 'inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600' do %>
        <svg class="-ml-0.5 mr-1.5 h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path d="M10.75 4.75a.75.75 0 00-1.5 0v4.5h-4.5a.75.75 0 000 1.5h4.5v4.5a.75.75 0 001.5 0v-4.5h4.5a.75.75 0 000-1.5h-4.5v-4.5z" />
        </svg>
        New Bookmark
      <% end %>
    </div>
  </div>
<% end %>

app/views/bookmarks/new.html.erb
<div class="mx-auto max-w-2xl py-14">
  <div>
    <h1 class="text-3xl font-semibold text-gray-900 mb-2">New Bookmark</h1>
  </div>
  <%= render 'form' %>
</div>

app/views/bookmarks/show.html.erb
<div class="mx-auto max-w-2xl py-14">
  <div class="flex flex-col gap-12">
    <div>
      <h1 class="text-3xl font-semibold text-gray-900 mb-2">
        <%= @bookmark.title %>
      </h1>
      <div class="text-sm truncate text-gray-600">
        <%= link_to @bookmark.url, @bookmark.url %>
      </div>
    </div>
    <% if @bookmark.tags.any? %>
      <div>
        <div class="flex flex-row gap-2 flex-wrap">
          <% @bookmark.tags.each do |tag| %>
            <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800">
              <%= tag.name %>
            </span>
          <% end %>
        </div>
      </div>
    <% end %>
    <% if @bookmark.notes? %>
      <div>
        <div class="prose">
          <%= markdown(@bookmark.notes).html_safe %>
        </div>
      </div>
    <% end %>
    <div>
      <div class="flex flex-row gap-2">
        <%= button_to @bookmark, data: { turbo_confirm: 'Are you sure?' }, method: :delete, class: 'inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50' do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
          </svg>
        <% end %>
        <%= link_to 'Edit', edit_bookmark_path(@bookmark), class: 'inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50' %>
        <%= link_to 'Back', bookmarks_path, class: 'inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-gray-700 hover:bg-gray-800' %>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bookmarks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.css">
    <script src="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.js"></script>
  </head>
  <body class="grid grid-rows-[auto,1fr,auto] min-h-screen">
    <%= render "shared/navbar" %>
    <main>
      <div class="container mx-auto h-full px-4">
        <%= render "shared/flash", flash: flash %>
        <%= yield %>
      </div>
    </main>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div
    data-controller="flash"
    data-transition-enter="transition ease-out duration-100"
    data-transition-enter-start="transform opacity-0 scale-95"
    data-transition-enter-end="transform opacity-100 scale-100"
    data-transition-leave="transition ease-in duration-75"
    data-transition-leave-start="transform opacity-100 scale-100"
    data-transition-leave-end="transform opacity-0 scale-95"
    class="hidden lg:max-w-md fixed top-5 right-1/2 translate-x-1/2 z-100 <%= classes_for_flash(key) %> py-3 px-5 rounded-lg"
  >
    <div class="flex items-center">
      <div class="mr-4"><%= value %></div>
      <button type="button" data-action="flash#dismiss">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
        </svg>
      </button>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-gray-50 py-6 px-10">
  <div class="flex items-center justify-between">
    <div>
      <%= link_to "https://github.com/christopherstyles/bookmarks" do %>
        <%= feather_icon "github", width: '24', height: '24' %>
      <% end %>
    </div>
    <div>
      <% if user_signed_in? %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Login', new_user_session_path %>
      <% end %>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="bg-white py-6 px-10 flex justify-between items-center">
  <div class="flex gap-6">
    <%= link_to root_url do %>
      Home
    <% end %>
    <div>
      <%= link_to 'New Bookmark', new_bookmark_path %>
    </div>
  </div>
  <div class="flex items-center gap-8">
    <% if user_signed_in? %>
      <div class="min-w-[350px]">
        <%= form_tag(search_bookmarks_path, method: :get, class: "flex items-center gap-1 w-full") do %>
          <div class="w-full sm:max-w-xs">
            <label for="search" class="sr-only">Search</label>
            <div class="relative">
              <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
                <svg class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" d="M9 3.5a5.5 5.5 0 100 11 5.5 5.5 0 000-11zM2 9a7 7 0 1112.452 4.391l3.328 3.329a.75.75 0 11-1.06 1.06l-3.329-3.328A7 7 0 012 9z" clip-rule="evenodd"></path>
                </svg>
              </div>
              <%= search_field_tag :q, params[:query], autocorrect: 'off', autocomplete: 'off', autocapitalize: 'none', class: "block w-full rounded-full border-0 bg-white py-1.5 pl-10 pr-3 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6", placeholder: "Search" %>
            </div>
          </div>
          <button type="submit" class="bg-gray-100 rounded-full text-gray-900 p-2 text-base cursor-pointer">
            <%= feather_icon('search', width: '18', height: '18', class: 'text-gray-600') %>
          </button>
        <% end %>
      </div>
      <div>
        <%= link_to 'Profile', edit_user_registration_path %>
      </div>
      <div>
        <%= button_to "Logout", destroy_user_session_path, method: :delete %>
      </div>
    <% else %>
      <%= link_to 'Login', new_user_session_path %>
    <% end %>
  </div>
</nav>